---
title: "Project"
output: html_document
date: "2022-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Data Ingestion and Cleaning}
library(tidyverse)
library(readxl)
library(fpp3)
library(readabs)
library(tidyverse)
library(tidyr)
library(fpp3)
library(keras)
library(tensorflow)
library(caret)

#save(model_var, file="my_model.rda")
#model %>%
#  save_model_hdf5("lstm_model_6.h5")



countries <- read_excel("country_assoc.xlsx") %>% mutate(AreaCode = areacode) %>% select(AreaCode,AreaName)


data2014_12 <- read_excel("2014_12_ActualTotalLoad.xlsx")
data2014 <- data2014_12

data2015_1 <- read_excel("2015_1_ActualTotalLoad.xlsx")
data2015_2 <- read_excel("2015_2_ActualTotalLoad.xlsx")
data2015_3 <- read_excel("2015_3_ActualTotalLoad.xlsx")
data2015_4 <- read_excel("2015_4_ActualTotalLoad.xlsx")
data2015_5 <- read_excel("2015_5_ActualTotalLoad.xlsx")
data2015_6 <- read_excel("2015_6_ActualTotalLoad.xlsx")
data2015_7 <- read_excel("2015_7_ActualTotalLoad.xlsx")
data2015_8 <- read_excel("2015_8_ActualTotalLoad.xlsx")
data2015_9 <- read_excel("2015_9_ActualTotalLoad.xlsx")
data2015_10 <- read_excel("2015_10_ActualTotalLoad.xlsx")
data2015_11 <- read_excel("2015_11_ActualTotalLoad.xlsx")
data2015_12 <- read_excel("2015_12_ActualTotalLoad.xlsx")
data2015 <- bind_rows(data2015_1,data2015_2,data2015_3,data2015_4,data2015_5,data2015_6,data2015_7,data2015_8,data2015_9,data2015_10,data2015_11,data2015_12)

data2016_1 <- read_excel("2016_1_ActualTotalLoad.xlsx")
data2016_2 <- read_excel("2016_2_ActualTotalLoad.xlsx")
data2016_3 <- read_excel("2016_3_ActualTotalLoad.xlsx")
data2016_4 <- read_excel("2016_4_ActualTotalLoad.xlsx")
data2016_5 <- read_excel("2016_5_ActualTotalLoad.xlsx")
data2016_6 <- read_excel("2016_6_ActualTotalLoad.xlsx")
data2016_7 <- read_excel("2016_7_ActualTotalLoad.xlsx")
data2016_8 <- read_excel("2016_8_ActualTotalLoad.xlsx")
data2016_9 <- read_excel("2016_9_ActualTotalLoad.xlsx")
data2016_10 <- read_excel("2016_10_ActualTotalLoad.xlsx")
data2016_11 <- read_excel("2016_11_ActualTotalLoad.xlsx")
data2016_12 <- read_excel("2016_12_ActualTotalLoad.xlsx")
data2016 <- bind_rows(data2016_1,data2016_2,data2016_3,data2016_4,data2016_5,data2016_6,data2016_7,data2016_8,data2016_9,data2016_10,data2016_11,data2016_12)

data2017_1 <- read_excel("2017_1_ActualTotalLoad.xlsx")
data2017_2 <- read_excel("2017_2_ActualTotalLoad.xlsx")
data2017_3 <- read_excel("2017_3_ActualTotalLoad.xlsx")
data2017_4 <- read_excel("2017_4_ActualTotalLoad.xlsx")
data2017_5 <- read_excel("2017_5_ActualTotalLoad.xlsx")
data2017_6 <- read_excel("2017_6_ActualTotalLoad.xlsx")
data2017_7 <- read_excel("2017_7_ActualTotalLoad.xlsx")
data2017_8 <- read_excel("2017_8_ActualTotalLoad.xlsx")
data2017_9 <- read_excel("2017_9_ActualTotalLoad.xlsx")
data2017_10 <- read_excel("2017_10_ActualTotalLoad.xlsx")
data2017_11 <- read_excel("2017_11_ActualTotalLoad.xlsx")
data2017_12 <- read_excel("2017_12_ActualTotalLoad.xlsx")
data2017 <- bind_rows(data2017_1,data2017_2,data2017_3,data2017_4,data2017_5,data2017_6,data2017_7,data2017_8,data2017_9,data2017_10,data2017_11,data2017_12)

data2018_1 <- read_excel("2018_1_ActualTotalLoad.xlsx")
data2018_2 <- read_excel("2018_2_ActualTotalLoad.xlsx")
data2018_3 <- read_excel("2018_3_ActualTotalLoad.xlsx")
data2018_4 <- read_excel("2018_4_ActualTotalLoad.xlsx")
data2018_5 <- read_excel("2018_5_ActualTotalLoad.xlsx")
data2018_6 <- read_excel("2018_6_ActualTotalLoad.xlsx")
data2018_7 <- read_excel("2018_7_ActualTotalLoad.xlsx")
data2018_8 <- read_excel("2018_8_ActualTotalLoad.xlsx")
data2018_9 <- read_excel("2018_9_ActualTotalLoad.xlsx")
data2018_10 <- read_excel("2018_10_ActualTotalLoad.xlsx")
data2018_11 <- read_excel("2018_11_ActualTotalLoad.xlsx")
data2018_12 <- read_excel("2018_12_ActualTotalLoad.xlsx")
data2018 <- bind_rows(data2018_1,data2018_2,data2018_3,data2018_4,data2018_5,data2018_6,data2018_7,data2018_8,data2018_9,data2018_10,data2018_11,data2018_12)

data2019_1 <- read_excel("2019_1_ActualTotalLoad.xlsx")
data2019_2 <- read_excel("2019_2_ActualTotalLoad.xlsx")
data2019_3 <- read_excel("2019_3_ActualTotalLoad.xlsx")
data2019_4 <- read_excel("2019_4_ActualTotalLoad.xlsx")
data2019_5 <- read_excel("2019_5_ActualTotalLoad.xlsx")
data2019_6 <- read_excel("2019_6_ActualTotalLoad.xlsx")
data2019_7 <- read_excel("2019_7_ActualTotalLoad.xlsx")
data2019_8 <- read_excel("2019_8_ActualTotalLoad.xlsx")
data2019_9 <- read_excel("2019_9_ActualTotalLoad.xlsx")
data2019_10 <- read_excel("2019_10_ActualTotalLoad.xlsx")
data2019_11 <- read_excel("2019_11_ActualTotalLoad.xlsx")
data2019_12 <- read_excel("2019_12_ActualTotalLoad.xlsx")
data2019 <- bind_rows(data2019_1,data2019_2,data2019_3,data2019_4,data2019_5,data2019_6,data2019_7,data2019_8,data2019_9,data2019_10,data2019_11,data2019_12)

data1 <- bind_rows(data2014,data2015,data2016,data2017,data2018,data2019)
data1$Date <- as.Date(data1$DateTime)
data1$Time <- format(data1$DateTime, "%H:%M:%S")
data1$Hours <- format(as.POSIXct(data1$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%H")
data1$Minutes <- format(as.POSIXct(data1$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%M")
data1$Day <- format(as.POSIXct(data1$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%d")
data1$Year <- format(as.POSIXct(data1$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%Y")
data1$Month <- format(as.POSIXct(data1$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%m")
data1 <- data1 %>% mutate(AreaCode = areacode) %>% select(DateTime, Year, Month, Day, Hours, Minutes, AreaName, AreaCode, AreaTypeCode, ResolutionCode, TotalLoadValue)

#data2020_1 <- read_excel("2020_1_ActualTotalLoad.xlsx")
#data2020_2 <- read_excel("2020_2_ActualTotalLoad.xlsx")
#data2020_3 <- read_excel("2020_3_ActualTotalLoad.xlsx")
#data2020_4 <- read_excel("2020_4_ActualTotalLoad.xlsx")
#data2020_5 <- read_excel("2020_5_ActualTotalLoad.xlsx")
#data2020_6 <- read_excel("2020_6_ActualTotalLoad.xlsx")
#data2020_7 <- read_excel("2020_7_ActualTotalLoad.xlsx")

data2020_01 <- read_excel("2020_01_ActualTotalLoad_6.1.A.xlsx")
data2020_02 <- read_excel("2020_02_ActualTotalLoad_6.1.A.xlsx")
data2020_03 <- read_excel("2020_03_ActualTotalLoad_6.1.A.xlsx")
data2020_04 <- read_excel("2020_04_ActualTotalLoad_6.1.A.xlsx")
data2020_05 <- read_excel("2020_05_ActualTotalLoad_6.1.A.xlsx")
data2020_06 <- read_excel("2020_06_ActualTotalLoad_6.1.A.xlsx")
data2020_07 <- read_excel("2020_07_ActualTotalLoad_6.1.A.xlsx")
data2020_08 <- read_excel("2020_08_ActualTotalLoad_6.1.A.xlsx")
data2020_09 <- read_excel("2020_09_ActualTotalLoad_6.1.A.xlsx")
data2020_10 <- read_excel("2020_10_ActualTotalLoad_6.1.A.xlsx")
data2020_11 <- read_excel("2020_11_ActualTotalLoad_6.1.A.xlsx")
data2020_12 <- read_excel("2020_12_ActualTotalLoad_6.1.A.xlsx")
data2020 <- bind_rows(data2020_01,data2020_02,data2020_03,data2020_04,data2020_05,data2020_06,data2020_07,data2020_08,data2020_09,data2020_10,data2020_11,data2020_12)


data2021_01 <- read_excel("2021_01_ActualTotalLoad_6.1.A.xlsx")
data2021_02 <- read_excel("2021_02_ActualTotalLoad_6.1.A.xlsx")
data2021_03 <- read_excel("2021_03_ActualTotalLoad_6.1.A.xlsx")
data2021_04 <- read_excel("2021_04_ActualTotalLoad_6.1.A.xlsx")
data2021_05 <- read_excel("2021_05_ActualTotalLoad_6.1.A.xlsx")
data2021_06 <- read_excel("2021_06_ActualTotalLoad_6.1.A.xlsx")
data2021 <- bind_rows(data2021_01,data2021_02,data2021_03,data2021_04,data2021_05,data2021_06)

data2 <- bind_rows(data2020,data2021)
data2$Date <- as.Date(data2$DateTime)
data2$Time <- format(data2$DateTime, "%H:%M:%S")
data2$Hours <- format(as.POSIXct(data2$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%H")
data2$Minutes <- format(as.POSIXct(data2$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%M")
data2$Day <- format(as.POSIXct(data2$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%d")
data2$Year <- format(as.POSIXct(data2$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%Y")
data2$Month <- format(as.POSIXct(data2$DateTime, "%Y-%m-%d %H:%M:%S", tz = ""), format = "%m")
data2 <- data2 %>% select(DateTime, Year, Month, Day, Hours, Minutes, AreaName, AreaCode, AreaTypeCode, ResolutionCode, TotalLoadValue)


all_data <- bind_rows(data1,data2)

filtered_all_data <- all_data %>% filter(AreaTypeCode == "CTY") %>% inner_join(countries, by="AreaCode") %>% mutate(AreaName = AreaName.y, Month = as.numeric(Month), Day = as.numeric(Day), Hours = as.numeric(Hours), Minutes = as.numeric(Minutes), Year = as.numeric(Year)) %>% select(DateTime, Year, Month, Day, Hours, Minutes, AreaName, ResolutionCode, TotalLoadValue) %>%  mutate(dayofweek = ifelse(weekdays(DateTime) %in% c("Saturday", "Sunday"), 1, 0))

filtered_all_data <- filtered_all_data %>% group_by(Year, Month, Day, Hours, AreaName, dayofweek) %>% summarise(TotalLoadValue = sum(TotalLoadValue))



######## - Upload data.csv
write.csv(filtered_all_data, "nn_data.csv")
data <- read_csv("nn_data.csv") %>% filter(AreaName == "Austria")

# Check for NA's
colSums(is.na(data))

# Summary for all columns
sapply(data, summary)

ymd
```

```{r}
data <- read_csv("../data/nn_data.csv") %>% filter(AreaName == "Austria")
# Check for NA's
colSums(is.na(data))

# Summary for all columns
sapply(data, summary)
```


------------------------------------------

```{r, EDA}
# Between countries
ggplot(data=data, aes(x=reorder(AreaName,TotalLoadValue),y=mean(TotalLoadValue))) + geom_bar(stat='identity', aes(fill=mean(TotalLoadValue))) + coord_flip()

# Yearly plots
eda_data_year <- data %>% filter(AreaName %in% c('France', 'Germany', 'Belgium'))
eda_data_year %>% ggplot(aes(x=DateTime, y=TotalLoadValue, colour = Year)) + geom_line() + facet_wrap(~AreaName)
eda_data_year %>% filter(Year %in% c(2015,2016,2017,2018,2019)) %>% group_by(Year, AreaName) %>% summarise(TotalLoadValue = sum(TotalLoadValue)) %>% ggplot(aes(x=Year, y=TotalLoadValue)) + geom_point() + facet_wrap(~AreaName)

# Monthly plots
eda_data_month <- data %>% filter(AreaName %in% c('France', 'Germany', 'Belgium'), Year %in% c(2017,2018,2019,2020))
eda_data_month %>% group_by(Year, Month, AreaName) %>% summarise(TotalLoadValue = sum(TotalLoadValue)) %>% ggplot(aes(x=Month, y=TotalLoadValue, colour = AreaName)) + geom_point() + facet_wrap(~Year)

# Weekly plots
eda_data_week <- data %>% filter(AreaName %in% c('France', 'Germany', 'Belgium'), Year %in% c(2017,2018,2019,2020))
eda_data_week %>% group_by(Dayofweek, AreaName) %>% summarise(TotalLoadValue = sum(TotalLoadValue)) %>% ggplot(aes(x=Dayofweek, y=TotalLoadValue, colour = AreaName)) + geom_point()

# Daily plots
eda_data_day <- data %>% group_by(Year, Month, Day, AreaName, Hours) %>% summarise(TotalLoadValue = sum(TotalLoadValue))
eda_data_day %>% filter(Month == 5, Year == 2019, Day %in% c(5,10,15)) %>% ggplot(aes(x=Hours, y=TotalLoadValue, colour = AreaName)) + geom_point() + facet_wrap(~Day)

# Hourly plots - Hours shouldn be used and period/resolution code
eda_data_hours <- data %>% group_by(AreaName, Minutes) %>% summarise(TotalLoadValue = sum(TotalLoadValue))
eda_data_hours %>% filter(Month == 5, Year == 2019, Day %in% c(5,10,15)) %>% ggplot(aes(x=Hours, y=TotalLoadValue, colour = AreaName)) + geom_point() + facet_wrap(~Day)
```


------------------------------------------

```{r, Baseline model}

```


------------------------------------------
```{r, NN}
data <- data %>% select(Year, Month, Day, Hours, dayofweek, TotalLoadValue)

# Try without lagged variables

# Try without scaling

# Try with scaling and lagged variables

# Create unstandardised dataset
lagged_data_usd <- data %>% mutate("hour-1" = lag(TotalLoadValue, n=1), "hour-2" = lag(TotalLoadValue, n=2) ,"day-1" = lag(TotalLoadValue, n=24), "day-7" = lag(TotalLoadValue, n=168)) %>% select(Year, Month, Day, Hours, dayofweek, TotalLoadValue, `day-1`, `day-7`, `hour-1`, `hour-2`) %>% tail(-168)

# Create standardised dataset
lagged_data_sd <- data %>% mutate("hour-1" = lag(TotalLoadValue, n=1), "hour-2" = lag(TotalLoadValue, n=2) ,"day-1" = lag(TotalLoadValue, n=24), "day-7" = lag(TotalLoadValue, n=168)) %>% select(Year, Month, Day, Hours, dayofweek, TotalLoadValue, `day-1`, `day-7`, `hour-1`, `hour-2`) %>% mutate(`day-1`= sqrt(`day-1`), `day-7`= sqrt(`day-7`), `hour-1`= sqrt(`hour-1`), `hour-2`= sqrt(`hour-2`)) %>% tail(-168)


#mutate(`day-1`= scale(`day-1`, center=TRUE, scale=TRUE), `day-7`= scale(`day-7`, center=TRUE, scale=TRUE), `hour-1`= scale(`hour-1`, center=TRUE, scale=TRUE), `hour-2`= scale(`hour-2`, center=TRUE, scale=TRUE)) %>% tail(-168)
#lagged_data <- data %>% select(Year, Month, Day, Hours, dayofweek, TotalLoadValue)

# Sin/cosine transform the time variables
lagged_data_sd$Hours_sin = sin(2*pi*lagged_data_sd$Hours/24)
lagged_data_sd$Hours_cos = cos(2*pi*lagged_data_sd$Hours/24)
lagged_data_sd$Month_sin = cos(2*pi*lagged_data_sd$Month/12)
lagged_data_sd$Month_cos = cos(2*pi*lagged_data_sd$Month/12)
lagged_data_sd$Day_sin = cos(2*pi*lagged_data_sd$Day/31)
lagged_data_sd$Day_cos = cos(2*pi*lagged_data_sd$Day/31)


lagged_data_usd$Hours_sin = sin(2*pi*lagged_data_usd$Hours/24)
lagged_data_usd$Hours_cos = cos(2*pi*lagged_data_usd$Hours/24)
lagged_data_usd$Month_sin = cos(2*pi*lagged_data_usd$Month/12)
lagged_data_usd$Month_cos = cos(2*pi*lagged_data_usd$Month/12)
lagged_data_usd$Day_sin = cos(2*pi*lagged_data_usd$Day/31)
lagged_data_usd$Day_cos = cos(2*pi*lagged_data_usd$Day/31)

# Remove outliers
lagged_data_sd <- lagged_data_sd[!lagged_data_sd$TotalLoadValue %in% boxplot.stats(lagged_data_sd$TotalLoadValue)$out,]
lagged_data_usd <- lagged_data_usd[!lagged_data_usd$TotalLoadValue %in% boxplot.stats(lagged_data_usd$TotalLoadValue)$out,]

# Train/Test split
#find_row_number <- lagged_data_sd %>% mutate(rownum <- row_number()) %>% filter(Year == 2019, Month == 10, Day == 19)
train <- lagged_data_sd[1:42380,] 
test <- lagged_data_sd[42381:nrow(lagged_data_sd),]

X_train = train %>% select(-Year, -TotalLoadValue, -Hours, -Day, -Month)
y_train = train %>% select(TotalLoadValue)

X_test = test %>% select(-Year, -TotalLoadValue, -Hours, -Day, -Month)
y_test = test %>% select(TotalLoadValue)


#For predicting and comparing to test set after
test_pred <- lagged_data_usd[42381:nrow(lagged_data_usd),] %>% mutate(`day-1`= sqrt(`day-1`), `day-7`= sqrt(`day-7`), `hour-1`= sqrt(`hour-1`), `hour-2`= sqrt(`hour-2`))

X_test_pred <- test_pred %>% select(-Year, -TotalLoadValue, -Hours, -Day, -Month)
Y_test_pred = test %>% select(TotalLoadValue) %>% mutate(TotalLoadValue = TotalLoadValue)
```


```{r, hyperparamter tuning}

```




```{r}
set.seed("2022")
model1 <- keras_model_sequential() %>%
  layer_dense(64, activation = "relu") %>%
  layer_dense(64, activation = "relu") %>%
  layer_dense(1, activation = "linear")

model1 <- model1 %>% compile(optimizer = optimizer_adam(), loss = 'mean_absolute_error')

history1 <- model1 %>% fit(as.matrix(X_train), as.matrix(y_train), validation_split = 0.2, epochs = 15)
plot(history1)

```


```{r}
model2 <- keras_model_sequential() %>%
  layer_lstm(units = 64) %>%
  layer_dense(units = 64, activation="relu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 64, activation="relu") %>%
  layer_dropout(0.3) %>%
  layer_dense(1, activation="linear")

model2 <- model2 %>% compile(optimizer = optimizer_adam(), loss = 'mean_absolute_error')

history2 <- model2 %>% fit(as.matrix(X_train), as.matrix(y_train), validation_split = 0.2, epochs = 15)
plot(history2)
```


```{r}
#model3 <- keras_model_sequential() %>%
 # layer_simple_rnn(units = 32) %>%
  ##layer_dense(units = 64, activation="relu") %>%
  #layer_dense(units = 64, activation="relu") %>%
  #layer_dense(1, activation="linear")

#model3 <- model3 %>% compile(optimizer = optimizer_adam(), loss = 'mean_absolute_error')


#history3 <- model3 %>% fit(as.matrix(X_train), as.matrix(y_train), validation_split = 0.2, epochs = 15)
##plot(history3)
```


```{r, test_eval}
model1 %>% evaluate(as.matrix(X_test),as.matrix(y_test))
```

```{r}
train_graph <- train %>% mutate(rownumber = row_number())
y <- predict(model1, as.matrix(X_train))
x <- seq(1, nrow(y), length.out = nrow(y))

ggplot(train) + geom_line(aes(x=x, y = TotalLoadValue, colour = "data"), size = 0.1) + geom_line(data = data.frame(train_graph$rownumber,y), aes(x=train_graph$rownumber, y=y, colour="prediction"), size = 0.1)


train_actual_graph <- train[1:1000,]
train_graph <- train_graph[1:1000,]
y <- y[1:1000,]
x <- seq(1, 1000, length.out = 1000)

ggplot(train_actual_graph) + geom_line(aes(x=x, y = TotalLoadValue, colour = "data")) + geom_line(data = data.frame(train_graph$rownumber,y), aes(x=train_graph$rownumber, y=y, colour="prediction"))

```

```{r}
#append date
predictions <- data.frame(rownumber = numeric(0), prediction = numeric(0))
for (i in 1:nrow(X_test_pred)) {
  if (i == 1) {
    prediction_i <- sqrt(predict(model1, as.matrix(X_test_pred[i,])))
    predictions[i,] <- c(i, prediction_i)
  }
  
  else if (i > 1 & i < 25) {
    X_test_pred$`hour-1`[i] = prediction_i
    X_test_pred$`hour-2`[i] = X_test_pred$`hour-1`[i-1]
    prediction_i <- sqrt(predict(model1, as.matrix(X_test_pred[i,])))
    predictions[i,] <- c(i, prediction_i)
  }
  
  else if (i > 24 & i < 169) {
    X_test_pred$`hour-1`[i] = prediction_i
    X_test_pred$`hour-2`[i] = X_test_pred$`hour-1`[i-1]
    X_test_pred$`day-1`[i] = predictions[i-24,2]
    prediction_i <- sqrt(predict(model1, as.matrix(X_test_pred[i,])))
    predictions[i,] <- c(i, prediction_i)
  }
  else {
    X_test_pred$`hour-1`[i] = prediction_i
    X_test_pred$`hour-2`[i] = X_test_pred$`hour-1`[i-1]
    X_test_pred$`day-1`[i] = predictions[i-24,2]
    X_test_pred$`day-7`[i] = predictions[i-168,2]
    prediction_i <- sqrt(predict(model1, as.matrix(X_test_pred[i,])))
    predictions[i,] <- c(i, prediction_i)
  }
}

Y_test_pred


final_predictions <- predictions %>% mutate(TotalLoadValue = prediction^2) 
x <- seq(1, nrow(predictions), length.out = nrow(predictions))
ggplot(Y_test_pred) + geom_line(aes(x=x, y = TotalLoadValue, colour = "data")) + geom_line(data = final_predictions, aes(x=rownumber, y=TotalLoadValue, colour="prediction"))

final <- test
final$TotalLoadValuePred = final_predictions$TotalLoadValue


final <- final %>% group_by(Year, Month, Day) %>% summarise(TotalLoadValue = sum(TotalLoadValuePred))

write.csv(final, "../models/predictions/raw_nn_preds.csv")
```


```{r}
#- Learning rate
#- Early stopping 
#- Learning rate scheduler
#- Batch size
#- Weight decay (or normalisation)
#- Drop out
#- Dense layer units
#- 
```

