---
title: "train_dhr"
author: "Ayden Zein Khalil 30604265"
date: '2022-10-06'
output: html_document
---


```{r}
library(fpp3)
library(dplyr)
```

```{r}
TEST_START_DATE = "2019-10-18"

data <- read.csv("../data/all_data_daily.csv") %>% 
  mutate(Date = as.Date(Date, "%Y-%m-%d"))

data_train <- data %>% filter(Date < TEST_START_DATE)
``` 


```{r}
elec_austria <- data_train %>% filter(Country=="Austria") %>% 
  select(Date, TotalLoadValue) %>% as_tsibble() 
```

```{r}
elec_austria_fit <- elec_austria %>% 
  model(
    dhr = ARIMA(TotalLoadValue ~ fourier(period="year", K=4), 
                stepwise=FALSE, order_constraint = (p+q <= 6 & P+Q <= 2)),
    arima = ARIMA(TotalLoadValue, stepwise=FALSE, 
                  order_constraint = (p+q <= 6 & P+Q <= 2)),
    ets = ETS(TotalLoadValue)
  )

accuracy(elec_austria_fit)
```

We notice that the DHR model has the lowest MAE, MAPE and RMSSE. 


```{r}
forecast(elec_austria_fit, h = 730) %>% 
  autoplot(elec_austria %>% filter(Date >= "2017-06-01"))
```

From these forecasts we see that the DHR also does the best in picking up 
the seasonal/cyclical behaviors.


```{r}
# Model Details
dhr_mod = elec_austria_fit$dhr
dhr_mod %>% report()
```

We see that the model is an a regression with K=4 Fourier terms and ARIMA(5,0,1)(2,1,0)[7] errors.


```{r}
## Save Model
save(dhr_mod, file="../models/austria_dhr.rda")
```


### We tried other countries as well, as we see that the grid search does not provide as good a fit.

```{r}
elec_belgium <- data_train %>% filter(Country=="Belgium") %>% 
  select(Date, TotalLoadValue) %>% as_tibble()

elec_spain <- data_train %>% filter(Country=="Spain") %>% 
  select(Date, TotalLoadValue) %>% as_tibble()

elec_croatia <- data_train %>% filter(Country=="Croatia") %>% 
  select(Date, TotalLoadValue) %>% as_tibble()

elec_italy <- data_train %>% filter(Country=="Italy") %>% 
  select(Date, TotalLoadValue) %>% as_tibble()
```

```{r}
elec_belgium_fit <- elec_belgium %>% fill_gaps() %>%
  model(
    dhr = ARIMA(TotalLoadValue ~ fourier(period="year", K=4), 
                stepwise=FALSE,
                order_constraint = (p+q <= 6 & P+Q <= 2))
  )

accuracy(elec_belgium_fit)

autoplot(elec_belgium)

forecast(elec_belgium_fit, h = 730) %>% 
  autoplot(elec_belgium %>% filter(Date >= "2017-06-01"))
```

```{r}
elec_spain_fit <- elec_spain %>% fill_gaps() %>%
  model(
    dhr = ARIMA(TotalLoadValue ~ fourier(period="year", K=4), 
                stepwise=FALSE,
                order_constraint = (p+q <= 6 & P+Q <= 2))
  )

accuracy(elec_spain_fit)

autoplot(elec_spain)

forecast(elec_spain_fit, h = 730) %>% autoplot(elec_spain %>% filter(Date >= "2017-06-01"))
```

```{r}
elec_croatia_fit <- elec_croatia %>% fill_gaps() %>%
  model(
    dhr = ARIMA(TotalLoadValue ~ fourier(period="year", K=4), 
                stepwise=FALSE,
                order_constraint = (p+q <= 6 & P+Q <= 2))
  )

accuracy(elec_croatia_fit)

autoplot(elec_croatia)

forecast(elec_croatia_fit, h = 730) %>% autoplot(elec_croatia %>% filter(Date >= "2017-06-01"))
```


```{r}
elec_italy_fit <- elec_italy %>% fill_gaps() %>%
  model(
    dhr = ARIMA(TotalLoadValue ~ fourier(period="year", K=4), 
                stepwise=FALSE,
                order_constraint = (p+q <= 6 & P+Q <= 2))
  )

accuracy(elec_italy_fit)

autoplot(elec_italy)

forecast(elec_italy_fit, h = 730) %>% autoplot(elec_italy %>% filter(Date >= "2017-06-01"))
```