---
title: "model_eval"
author: "Ayden Zein Khalil"
date: '2022-10-12'
output: html_document
---

## Imports
```{r}
library(dplyr)
library(fpp3)
library(glue)
library(ggplot2)
library(Metrics)
```

## Globals
```{r}
TRAIN_START_DATE = "2014-12-01"
TRAIN_END_DATE = "2019-10-19"
TEST_START_DATE = "2019-10-18"
TEST_END_DATE = "2021-06-01"
```


## 1. Load Data & Models

### 1.1. DHR Data

```{r}
data = read.csv("../data/all_data_daily.csv") %>% 
    mutate(Date = as.Date(Date, "%Y-%m-%d")) %>% 
    filter(Country=="Austria") %>% 
    select(Date, TotalLoadValue) %>% 
    as_tsibble()

train = data %>% filter(
  Date >= TRAIN_START_DATE,
  Date <= TRAIN_END_DATE)

test = data %>% filter(
  Date >= TEST_START_DATE,
  Date <= TEST_END_DATE)

forecast_days = nrow(test)
```

### 1.2. Load DHR Model

```{r}
load("../models/austria_dhr.rda") # dhr_mod loaded
```


### 1.3. Load DHR Predictions

```{r}
dhr_preds <- dhr_mod %>% 
  forecast(h=forecast_days) %>% 
  as_tsibble(index=Date) %>%
  select(Date, .mean) %>%
  rename(TotalLoadValue = .mean)
```


### 1.4. Load NN Predictions
```{r}
nn_preds_raw <- read.csv("../models/predictions/raw_nn_preds.csv")

nn_preds <- nn_preds_raw %>% 
  mutate(Date = ymd(glue("{Year}-{Month}-{Day}"))) %>%
  select(Date, TotalLoadValue) %>% 
  filter(Date >= TEST_START_DATE, Date <= TEST_END_DATE) %>% 
  as_tsibble(index=Date)

l2_preds <- read.csv("../models/predictions/model_2.csv") %>% 
  mutate(Date = ymd(glue("{Year}-{Month}-{Day}"))) %>%
  select(Date, TotalLoadValue) %>% 
  filter(Date >= TEST_START_DATE, Date <= TEST_END_DATE) %>% 
  as_tsibble(index=Date)


l3_preds <- read.csv("../models/predictions/model_3layer.csv") %>% 
  mutate(Date = ymd(glue("{Year}-{Month}-{Day}"))) %>%
  select(Date, TotalLoadValue) %>% 
  filter(Date >= TEST_START_DATE, Date <= TEST_END_DATE) %>% 
  as_tsibble(index=Date)
```


## 2. Visual Forecasts

### 2.1. DHR Forecast
```{r}
forecast(dhr_mod, h = forecast_days) %>% 
  autoplot(train) + labs(title="DHR Forecasts: Austria")
```


### 2.2. NN Forecast

```{r}
plot_nn <- function(train, pred, title) {
  ggplot() + 
    geom_line(data=train, aes(x=Date, y=TotalLoadValue)) +
    geom_line(data=pred, aes(x=Date, y=TotalLoadValue), color="red") + 
    labs(title=title)
}

plot_nn(train, nn_preds, "NN Forecasts: Austria") + ylim(0, 1.4e6)
```

```{r}
plot_nn(train, l3_preds, "NN Forecasts: 3layer") + ylim(0, 1.4e6)
plot_nn(train, l2_preds, "NN Forecasts: 2layer") + ylim(0, 1.4e6)
```


### 2.3. Comparison

```{r}
cmap <- c("DHR" = "blue", "NN" = "red", "True" = "black")

ggplot() + 
  geom_line(data=test, aes(x=Date, y=TotalLoadValue, color="True")) +
  geom_line(data=nn_preds, aes(x=Date, y=TotalLoadValue, color="NN"), alpha=0.3) + 
  geom_line(data=dhr_preds, aes(x=Date, y=TotalLoadValue, color="DHR"), alpha=0.3) + 
  labs(color = "Legend", title="Test Set Prediction: Austria") + 
  scale_color_manual(values = cmap)

```


## 3. Metrics Comparison

```{r}
calc_metrics <- function(mod_preds, trues, labels) {
  rmses = c()
  maes = c()
  mapes = c()
  
  for (i in 1:length(mod_preds)) {
    preds = mod_preds[[i]]$TotalLoadValue
    
    rmses = append(rmses, rmse(preds, trues))
    maes = append(maes, mae(preds, trues))
    mapes = append(mapes, mape(preds, trues))
  }
  
  data.frame(
    .model = labels,
    RMSE = rmses,
    MAE = maes,
    MAPE = mapes
  )
  
}

mod_preds = list()
mod_preds[[1]] = dhr_preds
mod_preds[[2]] = nn_preds
mod_preds[[3]] = l3_preds
mod_preds[[4]] = l2_preds

calc_metrics(
  mod_preds, 
  test$TotalLoadValue, 
  c("DHR", "DefaultNet", "3Layer", "2Layer")) %>%
  arrange(MAPE)


```

## 4. Flexibility/Scalability Test


### 4.1. Load DHR Models & Data
```{r}
source("../src/train_dhr.R")

belgium_mod <- train_dhr_model(country="Belgium")
belgium_data <- load_dhr_data(country="Belgium")

italy_mod <- train_dhr_model(country="Italy")
italy_data <- load_dhr_data(country="Italy")

spain_mod <- train_dhr_model(country="Spain")
spain_data <- load_dhr_data(country="Spain")
```


### 4.2. Load NN Models & Data
```{r}
source("../src/train_dnn.R")

raw = read.csv("../data/all_data_hourly.csv") %>% 
    filter(AreaName == "Belgium") %>% 
    select(Year, Date, Month, Day, Hours, dayofweek, TotalLoadValue)


belgium_nn <- train_nn_model(country="Belgium")
belgium_data_nn <- load_nn_data(country="Belgium")

spain_nn <- train_nn_model(country="Spain")
spain_data_nn <- load_nn_data(country="Spain")

italy_nn <- train_nn_model(country="Italy")
italy_data_nn <- load_nn_data(country="Italy")
```

### 4.3. Generate DHR Predictions
```{r}
belgium_dhr_preds <- generate_dhr_preds_df(belgium_mod, forecast_days)
italy_dhr_preds <- generate_dhr_preds_df(italy_mod, forecast_days)
spain_dhr_preds <- generate_dhr_preds_df(spain_mod, forecast_days)
```

### 4.4. Generate NN Predictions
```{r}
belgium_nn_preds <- generate_nn_preds_df(belgium_nn, belgium_data_nn)
italy_nn_preds <- generate_nn_preds_df(italy_nn, italy_data_nn)
spain_nn_preds <- generate_nn_preds_df(spain_nn, spain_data_nn)
```

### 4.5. DHR Visual Forecasts
```{r}
belgium_mod %>% 
  forecast(h=forecast_days) %>% 
  autoplot(belgium_data$train) + labs(title="DHR Forecast Belgium")

italy_mod %>% 
  forecast(h=forecast_days) %>% 
  autoplot(italy_data$train) + labs(title="DHR Forecast Italy")

spain_mod %>% 
  forecast(h=forecast_days) %>% 
  autoplot(spain_data$train) + labs(title="DHR Forecast Spain")
```

### 4.6. DHR Visual Forecasts
```{r}
plot_nn(belgium_data_nn$train, belgium_nn_preds, "NN Forecasts: Belgium")
plot_nn(italy_data_nn$train, italy_nn_preds, "NN Forecasts: Belgium")
plot_nn(spain_data_nn$train, spain_nn_preds, "NN Forecasts: Belgium")
```

### 4.7. Model Comparison
```{r}
# Belgium
belgium_preds = list()
belgium_preds[[1]] = belgium_dhr_preds
belgium_preds[[2]] = belgium_nn_preds

calc_metrics(
  belgium_preds, 
  belgium_data$test$TotalLoadValue, 
  c("DHR", "NN")) %>%
  arrange(MAPE)

# Italy
italy_preds = list()
italy_preds[[1]] = italy_dhr_preds
italy_preds[[2]] = italy_nn_preds

calc_metrics(
  italy_preds, 
  italy_data$test$TotalLoadValue, 
  c("DHR", "NN")) %>%
  arrange(MAPE)

# Spain
spain_preds = list()
spain_preds[[1]] = spain_dhr_preds
spain_preds[[2]] = spain_nn_preds

calc_metrics(
  spain_preds, 
  spain_data$test$TotalLoadValue, 
  c("DHR", "NN")) %>%
  arrange(MAPE)
```

